In [1]:
import numpy as np
import pandas as pd

#Problem 4.2

In [2]:
# random seed for consistency
np.random.seed(42)

# 3 random 3x3 matrices with integers from -10 to 10
M1 = np.random.randint(-10, 11, size=(3, 3))
M2 = np.random.randint(-10, 11, size=(3, 3))
M3 = np.random.randint(-10, 11, size=(3, 3))

In [3]:
# Matrix 1
print("\nM1 =")
print(M1)
det1 = np.linalg.det(M1)
print(f"\nDeterminant of M1: {det1:.4f}")

if np.abs(det1) < 1e-10:
    print("\nMatrix 1 is singular (non-invertible).")
else:
    M1_inv = np.linalg.inv(M1)
    print("\nM1^(-1) =")
    print(M1_inv)
    print("\nM1 × M1^(-1) =")
    print(np.round(M1 @ M1_inv, 10))


M1 =
[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]

Determinant of M1: -88.0000

M1^(-1) =
[[ 0.90909091 -0.36363636 -1.15909091]
 [ 0.45454545 -0.18181818 -0.45454545]
 [ 0.13636364  0.04545455 -0.13636364]]

M1 × M1^(-1) =
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]


In [4]:
# Matrix 2
print("\nM2 =")
print(M2)
det2 = np.linalg.det(M2)
print(f"\nDeterminant of M2: {det2:.4f}")

if np.abs(det2) < 1e-10:
    print("\nMatrix 2 is singular (non-invertible).")
else:
    M2_inv = np.linalg.inv(M2)
    print("\nM2^(-1) =")
    print(M2_inv)
    print("\nM2 × M2^(-1) =")
    print(np.round(M2 @ M2_inv, 10))


M2 =
[[ 0 10 -7]
 [-3 -8 10]
 [-9  1 -5]]

Determinant of M2: -525.0000

M2^(-1) =
[[-0.05714286 -0.08190476 -0.08380952]
 [ 0.2         0.12       -0.04      ]
 [ 0.14285714  0.17142857 -0.05714286]]

M2 × M2^(-1) =
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


In [5]:
# Matrix 3
print("\nM3 =")
print(M3)
det3 = np.linalg.det(M3)
print(f"\nDeterminant of M3: {det3:.4f}")

if np.abs(det3) < 1e-10:
    print("\nMatrix 3 is singular (non-invertible).")
else:
    M3_inv = np.linalg.inv(M3)
    print("\nM3^(-1) =")
    print(M3_inv)
    print("\nM3 × M3^(-1) =")
    print(np.round(M3 @ M3_inv, 10))


M3 =
[[ -9  10 -10]
 [  1   1   6]
 [ -1   5   4]]

Determinant of M3: 74.0000

M3^(-1) =
[[-0.35135135 -1.21621622  0.94594595]
 [-0.13513514 -0.62162162  0.59459459]
 [ 0.08108108  0.47297297 -0.25675676]]

M3 × M3^(-1) =
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


#Problem 5

In [6]:
# Load the dataset
df = pd.read_csv('kc_house_data.csv')

# Drop columns to ignore
df = df.drop(columns=['id', 'date', 'zipcode'])

# Separate features and response
response = 'price'
features = [col for col in df.columns if col != response]

##5.1

In [7]:
# Compute statistics for each feature
stats = pd.DataFrame({
    'Average': df[features].mean(),
    'Min': df[features].min(),
    'Max': df[features].max(),
    'Variance': df[features].var()
})

print("\n--- Statistics for Each Feature ---\n")
print(stats.to_string())

# Lowest and highest average
lowest_avg_feature = stats['Average'].idxmin()
highest_avg_feature = stats['Average'].idxmax()
print("\n--- Average Analysis ---")
print(f"Feature with LOWEST average:  {lowest_avg_feature} = {stats.loc[lowest_avg_feature, 'Average']:.4f}")
print(f"Feature with HIGHEST average: {highest_avg_feature} = {stats.loc[highest_avg_feature, 'Average']:.4f}")

# Lowest and highest variance
lowest_var_feature = stats['Variance'].idxmin()
highest_var_feature = stats['Variance'].idxmax()
print("\n--- Variance Analysis ---")
print(f"Feature with LOWEST variance:  {lowest_var_feature} = {stats.loc[lowest_var_feature, 'Variance']:.4f}")
print(f"Feature with HIGHEST variance: {highest_var_feature} = {stats.loc[highest_var_feature, 'Variance']:.4f}")


--- Statistics for Each Feature ---

                    Average        Min           Max      Variance
bedrooms           3.370842     0.0000  3.300000e+01  8.650150e-01
bathrooms          2.114757     0.0000  8.000000e+00  5.931513e-01
sqft_living     2079.899736   290.0000  1.354000e+04  8.435337e+05
sqft_lot       15106.967566   520.0000  1.651359e+06  1.715659e+09
floors             1.494309     1.0000  3.500000e+00  2.915880e-01
waterfront         0.007542     0.0000  1.000000e+00  7.485226e-03
view               0.234303     0.0000  4.000000e+00  5.872426e-01
condition          3.409430     1.0000  5.000000e+00  4.234665e-01
grade              7.656873     1.0000  1.300000e+01  1.381703e+00
sqft_above      1788.390691   290.0000  9.410000e+03  6.857347e+05
sqft_basement    291.509045     0.0000  4.820000e+03  1.958727e+05
yr_built        1971.005136  1900.0000  2.015000e+03  8.627973e+02
yr_renovated      84.402258     0.0000  2.015000e+03  1.613462e+05
lat               47.560

##5.2

In [8]:
# Compute correlation of each feature with the response
correlations = df[features].corrwith(df[response])
corr_df = pd.DataFrame({
    'Feature': correlations.index,
    'Correlation with Price': correlations.values
}).sort_values(by='Correlation with Price', ascending=False)

print("\n--- Correlation Coefficients Table ---\n")
print(corr_df.to_string(index=False))

# Positively correlated features
positive_corr = correlations[correlations > 0]
print("\n--- Positively Correlated Features ---")
for feat, corr in positive_corr.sort_values(ascending=False).items():
    print(f"  {feat}: {corr:.4f}")

# Feature with highest positive correlation
highest_corr_feature = correlations.idxmax()
highest_corr_value = correlations.max()
print(f"\nFeature with HIGHEST positive correlation: {highest_corr_feature} = {highest_corr_value:.4f}")


--- Correlation Coefficients Table ---

      Feature  Correlation with Price
  sqft_living                0.702035
        grade                0.667434
   sqft_above                0.605567
sqft_living15                0.585379
    bathrooms                0.525138
         view                0.397293
sqft_basement                0.323816
     bedrooms                0.308350
          lat                0.307003
   waterfront                0.266369
       floors                0.256794
 yr_renovated                0.126434
     sqft_lot                0.089661
   sqft_lot15                0.082447
     yr_built                0.054012
    condition                0.036362
         long                0.021626

--- Positively Correlated Features ---
  sqft_living: 0.7020
  grade: 0.6674
  sqft_above: 0.6056
  sqft_living15: 0.5854
  bathrooms: 0.5251
  view: 0.3973
  sqft_basement: 0.3238
  bedrooms: 0.3083
  lat: 0.3070
  waterfront: 0.2664
  floors: 0.2568
  yr_renovated: 0.1264

##5.3

In [9]:
negative_corr = correlations[correlations < 0]
if len(negative_corr) > 0:
    print("\n--- Features with Negative Correlation ---")
    for feat, corr in negative_corr.sort_values().items():
        print(f"  {feat}: {corr:.4f}")
else:
    print("\nNo features with negative correlation coefficient were found.")


No features with negative correlation coefficient were found.
